# Generated by Django 3.2.18 on 2023-05-01 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to=None)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='places.place')),
            ],
        ),
    ]
