# Generated by Django 3.2.18 on 2023-05-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_image_special_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='special_id',
        ),
    ]
