# Generated by Django 3.2.18 on 2023-05-01 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_image_special_id'),
    ]

    operations = [
    ]
