# Generated by Django 3.2.18 on 2023-05-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_auto_20230501_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='details_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='geometry_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='map_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
