# Generated by Django 4.2 on 2023-05-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20230501_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['special_id']},
        ),
        migrations.AlterField(
            model_name='image',
            name='special_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
