# Generated by Django 4.2 on 2023-05-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='details_url',
            field=models.TextField(null=True, unique=True),
        ),
    ]
