# Generated by Django 4.2 on 2023-05-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_alter_place_details_url_alter_place_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content',
            field=models.ImageField(max_length=210, upload_to='./images'),
        ),
    ]
