# Generated by Django 4.2 on 2023-05-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_alter_image_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='details_url',
        ),
        migrations.RemoveField(
            model_name='place',
            name='geometry_type',
        ),
        migrations.RemoveField(
            model_name='place',
            name='map_title',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='type',
        ),
    ]
