# Generated by Django 4.2 on 2023-05-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0025_alter_image_options_rename_special_id_image_list_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['serial_number']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='list_id',
            new_name='serial_number',
        ),
    ]
