# Generated by Django 4.2 on 2023-05-12 23:45

from django.db import migrations


def set_default(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    places = Place.objects.all()
    for place in places:
        if not place.description_short:
            place.description_short = ''
        if not place.description_long:
            place.description_long = ''


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0026_alter_image_options_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default),
    ]
